apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polder.fullname" . }}-configmap
data:
  app_config.js: |
    window.__APP_CONFIG__ = {
        MAPBOX_TOKEN: {{ .Values.mapboxToken }},
        STAC_API: {{ .Values.stacApiUrl }},
        TILER_API: {{ .Values.tilerApiUrl }},
    };
