---
# Source: webapp-polder/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-webapp-polder
  labels:
    helm.sh/chart: webapp-polder-0.1.0
    app.kubernetes.io/name: webapp-polder
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: webapp-polder/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-polder-configmap
  labels:
    helm.sh/chart: webapp-polder-0.1.0
    app.kubernetes.io/name: webapp-polder
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
data: 
  app_config.js: |
    window.__APP_CONFIG__ = {
          MAPBOX_TOKEN: "pk.eyJ1IjoiZGV2c2VlZCIsImEiOiJnUi1mbkVvIn0.018aLhX0Mb0tdtaT2QNe2Q",
          STAC_API: "https://rx3hna9pbg.execute-api.eu-central-1.amazonaws.com",
          TILER_API: "https://zbrrek3x0i.execute-api.eu-central-1.amazonaws.com",
    };
---
# Source: webapp-polder/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-webapp-polder
  labels:
    helm.sh/chart: webapp-polder-0.1.0
    app.kubernetes.io/name: webapp-polder
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webapp-polder
    app.kubernetes.io/instance: test
---
# Source: webapp-polder/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webapp-polder
  labels:
    helm.sh/chart: webapp-polder-0.1.0
    app.kubernetes.io/name: webapp-polder
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp-polder
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        helm.sh/chart: webapp-polder-0.1.0
        app.kubernetes.io/name: webapp-polder
        app.kubernetes.io/instance: test
        app.kubernetes.io/version: "0.2.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: test-webapp-polder
      securityContext:
        {}
      containers:
        - name: webapp-polder
          securityContext:
            {}
          image: "ghcr.io/developmentseed/polder:dev"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/app_config.js
              name: webapp-polder-config
              subPath: app_config.js
      volumes:
        - configMap:
            name: webapp-polder-configmap
          name: webapp-polder-config
---
# Source: webapp-polder/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "test-webapp-polder-test-connection"
  labels:
    helm.sh/chart: webapp-polder-0.1.0
    app.kubernetes.io/name: webapp-polder
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['test-webapp-polder:80']
  restartPolicy: Never
